### ISSUE TITLE
Main website search is broken

### ISSUE THREAD

**Issue by iamgmd** [nuxt/modules#403] opened 2022-07-15 08:15 UTC
https://modules.nuxtjs.org/

![2022-07-15-09-14-17](https://user-images.githubusercontent.com/2772038/179182293-863da9e7-b737-4738-9f53-b558ac01eb2c.png)

**Comment by RidingACodeToStray** [comment] 2022-07-15 08:18
+1
![image](https://user-images.githubusercontent.com/23070493/179182937-80bdf7e1-04c2-415c-8103-e0a87fc8dbf9.png)

**Comment by kissu** [comment] 2022-07-15 11:19
Oddly enough, pulling the project locally and running it on dev works well.

**Comment by antfu** [comment] 2022-07-15 12:35
Seem to be related to rc.5 bump. I have locked the deploy to https://github.com/nuxt/modules/commit/7c9a42d07419ab61efc09af99135ee142e2dd008 and will investigate the cause.

**Comment by danielroe** [comment] 2022-07-20 21:02
@antfu Seems this might be caused by a directive missing an SSR transform: https://github.com/vuejs/vitepress/issues/92. I've  confirmed it's fixed when removing the `v-tooltip` directives in the project.

**Comment by then3rdman** [comment] 2022-07-21 09:49
Currently deployed site is unsable, so just bumping this

**Comment by antfu** [comment] 2022-07-29 06:41
Fixed in #410

**Closed by antfu** 2022-07-29 06:41 UTC
